---
# tasks file for sshuttle
- name: "install {{ sshuttle_package }} via {{ ansible_pkg_mgr }}"
  ansible.builtin.package:
    name: "{{ sshuttle_package }}"

- name: "add {{ sshuttle_group }}"
  group:
    name: "{{ sshuttle_group }}"
    state: present

- name: "Add {{ sshuttle_user }}"
  user:
    name: "{{ sshuttle_user }}"
    generate_ssh_key: yes
    state: present
  register: user_result

- name: "Add {{ sshuttle_host_ip }}"
  add_host:
    name: "{{ sshuttle_host_ip }}"
    groups: remote

- name: "Add ssh key to remote host"
  authorized_key:
    user: "{{ sshuttle_user }}"
    key: "{{ user_result.ssh_public_key }}"
    state: present
  when: invetory_hostname in groups['remote']

- name: add required sshuttle sudo privileges
  template:
    src: "sshuttle_sudoers.j2"
    dest: "/etc/sudoers.d/sshuttle"
    owner: root
    group: root
    mode: 0440

- name: create sshuttle unit file
  template:
    src: "sshuttle.service.j2"
    dest: "/etc/systemd/system/sshuttle.service"
    owner: root
    group: root
    mode: 0440
  notify: daemon reload

- name: ensure sshuttle directory exists
  file:
    state: directory
    path: /etc/sshuttle
    owner: "{{ sshuttle_user }}"
    group: "{{ sshuttle_group }}"
  register: sshuttle_dir

- name: add sshuttle start script
  template:
    src: sshuttle.py.j2
    dest: "{{ sshuttle_dir.path }}/shuttle.py"
    owner: "{{ sshuttle_user }}"
    group: "{{ sshuttle_group }}"
    mode: 0755
  notify: start sshuttle

- name: add sshuttle config.json
  template:
    src: config.json.j2
    dest: "{{ sshuttle_dir.path }}/config.json"
    owner: "{{ sshuttle_user }}"
    group: "{{ sshuttle_group }}"
    mode: 0644
  notify: restart sshuttle
