---
# tasks file for sshuttle
- name: "install {{ sshuttle_package }} via {{ ansible_pkg_mgr }}"
  ansible.builtin.package:
    name: "{{ sshuttle_package }}"

- name: "add {{ sshuttle_group }} group"
  group:
    name: "{{ sshuttle_group }}"
    state: present

- name: "Add {{ sshuttle_user }} user"
  user:
    name: "{{ sshuttle_user }}"
    generate_ssh_key: yes
    force: true
    ssh_key_file: ".ssh/sshuttle_rsa"
    state: present
  register: user_result

- name: ssh config block
  block:
    - name: "Add {{ remote_ip }} to inventory"
      add_host:
        name: "{{ remote_ip }}"
        groups: remote
        ansible_ssh_user: "{{ remote_username }}"
        ansible_ssh_password: "{{ remote_password }}"

    - name: "Add ssh key to remote host"
      authorized_key:
        user: "{{ sshuttle_user }}"
        key: "{{ user_result.ssh_public_key }}"
        state: present
      delegate_to: "{{ sshuttle_remote_ip }}"

    - name: "Register private key path value"
      set_fact:
        private_key_path: "{{ user_result.ssh_key_file }}"

    - name: "Create {{ remote_username }} ssh config"
      template:
        dest: "{{ user_result.home }}/.ssh/config"
        src: sshconfig.j2
        backup: true
  when: remote_auth

- name: add required sshuttle sudo privileges
  template:
    src: "sshuttle_sudoers.j2"
    dest: "/etc/sudoers.d/sshuttle"
    owner: root
    group: root
    mode: 0440

- name: "create sshuttle {{ ansible_service_mgr }} file"
  template:
    src: "{{ ansible_service_mgr }}.service.j2"
    dest: "{{ '/etc/systemd/system/sshuttle.service' if ansible_service_mgr == 'systemd' else '/etc/init.d/sshuttle' }}"
    owner: root
    group: root
    mode: 0440
  notify: daemon reload

- name: ensure sshuttle directory exists
  file:
    state: directory
    path: /etc/sshuttle
    owner: "{{ sshuttle_user }}"
    group: "{{ sshuttle_group }}"
  register: sshuttle_dir

- name: add sshuttle start script
  template:
    src: sshuttle.py.j2
    dest: "{{ sshuttle_dir.path }}/shuttle.py"
    owner: "{{ sshuttle_user }}"
    group: "{{ sshuttle_group }}"
    mode: 0755
  notify: start sshuttle

- name: add sshuttle config.json
  template:
    src: config.json.j2
    dest: "{{ sshuttle_dir.path }}/config.json"
    owner: "{{ sshuttle_user }}"
    group: "{{ sshuttle_group }}"
    mode: 0644
  notify: restart sshuttle
