---
# handlers file for sshuttle
- name: daemon reload
  systemd:
    daemon_reload: true
  listen: daemon_reload
  when: ansible_service_mgr == "systemd"
  become: true

- name: start sshuttle service
  service:
    name: sshuttle
    state: started
    enabled: true
  listen: start sshuttle
  when: remote_auth
  become: true

- name: restart sshuttle service
  service:
    name: sshuttle
    state: restarted
  listen: restart sshuttle
  become: true
