---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: sshuttle
    image: geerlingguy/docker-centos8-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
