---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: sshuttle
    image: centos-va:latest #docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
