---
- name: Converge
  hosts: all
  vars:
    remote_hostname: "remote-host"
    remote_ip: ""
    remote_user: "test"
    remote_password: "password"
    remote_auth: true
  tasks:
    - name: "Include ansible-role-sshuttle"
      include_role:
        name: "ansible-role-sshuttle"
